on: push
permissions:
  contents: write
jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "[" >catalog.json;c=;
          for f in *;do [ -f "$f" ]||continue;[ "${f:0:1}" = . ]&&continue;raw="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_REF_NAME/$f";
          if [[ "$f" == *.sune ]];then s=$(jq -c . "$f" 2>/dev/null||echo null);echo "$c  {\"name\":\"$f\",\"raw\":\"$raw\",\"sune\":$s}">>catalog.json;else echo "$c  {\"name\":\"$f\",\"raw\":\"$raw\"}">>catalog.json;fi;c=,;done
          echo "]" >>catalog.json
          t=$(mktemp);jq . catalog.json>"$t"&&mv "$t" catalog.json
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add catalog.json
          git commit -m update || true
          git push
