on: push
permissions:
  contents: write
jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "[" >catalog.json;c=;
          for f in *.sune;do [ -f "$f" ]||continue;raw="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_REF_NAME/$f";s=$(jq '.[0]|del(.avatar,.pinned,.settings.html,.settings.extension_html,.settings.script)' "$f" 2>/dev/null||echo null);n=$(jq -r '.[0].name//empty' "$f" 2>/dev/null);a=$(jq -r '.[0].avatar//empty' "$f" 2>/dev/null);jq -rn --arg name "${n:-$f}" --arg raw "$raw" --arg avatar "$a" --argjson s "$s" '({name:$name,raw:$raw}+(if $avatar=="" then {} else {avatar:$avatar} end)+{sune:[$s]})'|sed "1s/^/$c  /">>catalog.json;c=,;done
          echo "]" >>catalog.json
          t=$(mktemp);jq . catalog.json>"$t"&&mv "$t" catalog.json
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add catalog.json
          git commit -m update || true
          git push
